package application_test_jdbc;

import Utils.FichierConfig;
import beans.ConnectionOptions;
import beans.DataBaseAccessFactory;
import beans.IDataBaseAccess;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.crypto.SecretKey;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bobmastrolilli
 */
public class ClientGUI extends javax.swing.JFrame {

    DataBaseAccessFactory dbaf;
    IDataBaseAccess db;
    ConnectionOptions options;
    String STATE;
    /**
     * Creates new form ClientGUI
     */
    public ClientGUI() {
        initComponents();
        //buttonGroup1.add(this.RB_UPDATE);
        //buttonGroup1.add(this.RB_UPDATE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        Tabs = new javax.swing.JTabbedPane();
        TabConnexion = new javax.swing.JPanel();
        LB_machine = new javax.swing.JLabel();
        Connect_Bouton = new javax.swing.JButton();
        Deconnect_Bouton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        CB_ChooseSGBD = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTABLE_REQUEST = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TP_REQUEST = new javax.swing.JTextPane();
        TABLESMYSQL_CB = new javax.swing.JComboBox();
        RB_UPDATE = new javax.swing.JRadioButton();
        SELECT_RB = new javax.swing.JRadioButton();
        TableORACLE_CB = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client CheckIn");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Tabs.setToolTipText("");

        LB_machine.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LB_machine.setText("SGBD");

        Connect_Bouton.setText("Connect");
        Connect_Bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Connect_BoutonActionPerformed(evt);
            }
        });

        Deconnect_Bouton.setText("Disconnect");
        Deconnect_Bouton.setEnabled(false);
        Deconnect_Bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deconnect_BoutonActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Application TEST_JDBC");

        CB_ChooseSGBD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MySQL_BD_SOCIETE", "ORACLE_BD_JDB" }));

        javax.swing.GroupLayout TabConnexionLayout = new javax.swing.GroupLayout(TabConnexion);
        TabConnexion.setLayout(TabConnexionLayout);
        TabConnexionLayout.setHorizontalGroup(
            TabConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabConnexionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(TabConnexionLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel15)
                        .addGap(0, 545, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabConnexionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Connect_Bouton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Deconnect_Bouton)))
                .addContainerGap())
            .addGroup(TabConnexionLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(LB_machine)
                .addGap(22, 22, 22)
                .addComponent(CB_ChooseSGBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TabConnexionLayout.setVerticalGroup(
            TabConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabConnexionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(TabConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_machine)
                    .addComponent(CB_ChooseSGBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addGroup(TabConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deconnect_Bouton)
                    .addComponent(Connect_Bouton))
                .addContainerGap())
        );

        Tabs.addTab("Connexion", TabConnexion);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Requête SQL vers SGBD");

        JTABLE_REQUEST.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "c1", "c2", "c3", "c4", "c5"
            }
        ));
        jScrollPane1.setViewportView(JTABLE_REQUEST);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Requête : ");

        jScrollPane2.setViewportView(TP_REQUEST);

        TABLESMYSQL_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "APPAREILS", "TYPEAPPAREILS", "FOURNISSEURS", "CLIENTS", "VEHICULES", "PERSONNEL", "ITEMS_FACTURE", "FACTURES", "SALAIRES" }));

        buttonGroup1.add(RB_UPDATE);
        RB_UPDATE.setText("UPDATE");
        RB_UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_UPDATEActionPerformed(evt);
            }
        });

        buttonGroup1.add(SELECT_RB);
        SELECT_RB.setText("SELECT");

        TableORACLE_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACTIVITES", "INTERVENANTS" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(369, 369, 369)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RB_UPDATE)
                                    .addComponent(SELECT_RB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TABLESMYSQL_CB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TableORACLE_CB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator5)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TableORACLE_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(TABLESMYSQL_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(SELECT_RB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RB_UPDATE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(43, 43, 43)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        Tabs.addTab("Listing", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabs))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

}//GEN-LAST:event_formWindowClosing

    private void BT_verifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_verifierActionPerformed

    }//GEN-LAST:event_BT_verifierActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String request = this.TP_REQUEST.getText();
        System.out.println("Request = " + request);

        if (this.RB_UPDATE.isSelected()) {
            int retour = db.UpdateFromRequest(request);
            if (retour == 1) {
                JOptionPane.showMessageDialog(this, "Update réussie ! ", "Message connexion", JOptionPane.INFORMATION_MESSAGE, null);

            } else if (retour == 0) {
                JOptionPane.showMessageDialog(this, "Update a échoué ! ", "Message connexion", JOptionPane.INFORMATION_MESSAGE, null);

            }

        } 
        else {
            List<Object> res = new ArrayList<Object>();

            String nomTable = null;
            if(STATE == "ORACLE")
            {
                nomTable = this.TableORACLE_CB.getSelectedItem().toString();
            }
            else if(STATE == "MYSQL")
            {
                nomTable = this.TABLESMYSQL_CB.getSelectedItem().toString().trim();
            }
         
            res = db.SelectFromRequest(request, nomTable);
            
            DefaultTableModel dtm = (DefaultTableModel) this.JTABLE_REQUEST.getModel();
            for (int i = dtm.getRowCount(); i > 0; --i) {
                dtm.removeRow(i - 1);
            }

            for (int i = 0; i < res.size(); i++) {
                System.out.println(res.get(i));
                dtm.addRow((Vector) res.get(i));
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void Deconnect_BoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deconnect_BoutonActionPerformed

        closeConnection();
        JOptionPane.showMessageDialog(this, "Deonnexion à la DB! ", "Message Deconnexion", JOptionPane.INFORMATION_MESSAGE, null);
        Connect_Bouton.setEnabled(true);
        Deconnect_Bouton.setEnabled(false);
    }//GEN-LAST:event_Deconnect_BoutonActionPerformed

    private void Connect_BoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Connect_BoutonActionPerformed
        //TEST

        if (this.CB_ChooseSGBD.getSelectedIndex() == 1) //ORACLE
        {
            dbaf = DataBaseAccessFactory.getInstance();
            db = dbaf.getDataBaseAcces("Oracle");

            options = new ConnectionOptions();
            options.addOption("host", FichierConfig.getProperty("host"));
            options.addOption("port", FichierConfig.getProperty("portOracle"));
            options.addOption("database", FichierConfig.getProperty("DB_name_Oracle"));
            options.addOption("user", FichierConfig.getProperty("userOracle"));
            options.addOption("passwd", FichierConfig.getProperty("pwdOracle"));
            int test = db.Connect(options);
            if (test == 1) {
                JOptionPane.showMessageDialog(this, "Connexion à la DB Oracle Réussie ! ", "Message connexion", JOptionPane.INFORMATION_MESSAGE, null);
                this.Connect_Bouton.setEnabled(false);
                this.Deconnect_Bouton.setEnabled(true);
                STATE = "ORACLE";
            } else if (test == 0) {
                JOptionPane.showMessageDialog(this, "Echec de la connexion à la DB Oracle ! ", "Message connexion", JOptionPane.INFORMATION_MESSAGE, null);

            }
            this.TableORACLE_CB.setEnabled(true);
            this.TABLESMYSQL_CB.setEnabled(false);
        } else {
            dbaf = DataBaseAccessFactory.getInstance();
            db = dbaf.getDataBaseAcces("MySQL");

            options = new ConnectionOptions();
            options.addOption("host", FichierConfig.getProperty("host"));
            options.addOption("port", FichierConfig.getProperty("portMySQL"));
            options.addOption("database", FichierConfig.getProperty("DB_name_MySQL"));
            options.addOption("user", FichierConfig.getProperty("userMySQL"));
            options.addOption("passwd", FichierConfig.getProperty("pwdMySQL"));
            int test = db.Connect(options);
            if (test == 1) {
                JOptionPane.showMessageDialog(this, "Connexion à la DB MySQL Réussie ! ", "Message connexion", JOptionPane.INFORMATION_MESSAGE, null);
                this.Connect_Bouton.setEnabled(false);
                this.Deconnect_Bouton.setEnabled(true);
                STATE="MYSQL";
            } else if (test == 0) {

                JOptionPane.showMessageDialog(this, "Echec de la connexion à la DB MySQL ! ", "Message connexion", JOptionPane.INFORMATION_MESSAGE, null);
            }
            this.TableORACLE_CB.setEnabled(false);
            this.TABLESMYSQL_CB.setEnabled(true);
        }
        


    }//GEN-LAST:event_Connect_BoutonActionPerformed

    private void RB_UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_UPDATEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_UPDATEActionPerformed

    public void closeConnection() {
        db.Close();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CB_ChooseSGBD;
    private javax.swing.JButton Connect_Bouton;
    private javax.swing.JButton Deconnect_Bouton;
    private javax.swing.JTable JTABLE_REQUEST;
    private javax.swing.JLabel LB_machine;
    private javax.swing.JRadioButton RB_UPDATE;
    private javax.swing.JRadioButton SELECT_RB;
    private javax.swing.JComboBox TABLESMYSQL_CB;
    private javax.swing.JTextPane TP_REQUEST;
    private javax.swing.JPanel TabConnexion;
    private javax.swing.JComboBox TableORACLE_CB;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
